name: loan
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"         # any Dart 3.x from 3.4.0 up
  flutter: ">=3.22.0 <5.0.0"    # any Flutter 3.22+ (safe upper bound)

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.8
  loading_animation_widget: ^1.3.0
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5
  flutter_gen: ^5.5.0+1
  go_router: ^15.1.2
  get_it: ^8.0.3
  retrofit: ^4.1.0
  dio: ^5.4.3+1
  json_annotation: ^4.9.0
  pretty_dio_logger: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
  retrofit_generator: ^8.1.0
  intl: ^0.19.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/afn_logo.png